wandb_version: 1

learning_rate:
  desc: null
  value: 0.04
architecture:
  desc: null
  value: mobilenetv2
dataset:
  desc: null
  value: SFH_Dataset_S2CITIES_test_new_negatives_ratio1_224x224
epochs:
  desc: null
  value: 100
batch:
  desc: null
  value: 32
optimizer:
  desc: null
  value: SGD
sample_size:
  desc: null
  value: 112
sample_duration:
  desc: null
  value: 16
train_crop:
  desc: null
  value: corner
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1691145852.990906
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.10.12
      5: 0.15.8
      8:
      - 5
