wandb_version: 1

optimizer:
  desc: null
  value: SGD
lr:
  desc: null
  value: 0.001
lr_patience:
  desc: null
  value: 40
momentum:
  desc: null
  value: 0.9
dampening:
  desc: null
  value: 0.0
nesterov:
  desc: null
  value: true
weight_decay:
  desc: null
  value: 0.0
architecture:
  desc: null
  value: mobilenetv2
dataset:
  desc: null
  value: SFH_Dataset_S2CITIES_test_new_negatives_ratio1_224x224
epochs:
  desc: null
  value: 100
batch:
  desc: null
  value: 32
sample_size:
  desc: null
  value: 224
sample_duration:
  desc: null
  value: 16
train_crop:
  desc: null
  value: corner
early_stop_patience:
  desc: null
  value: 10
no_norm:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1691174207.972352
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.12
      5: 0.15.8
      8:
      - 5
